# Generated by Django 3.2.8 on 2021-12-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
